services:
  loki:
    restart: unless-stopped
    image: grafana/loki:3.4
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Blaataap_01
    networks:
      - logging
    depends_on:
      - loki

# Define the shared network
networks:
  logging:
    name: logging_network # Optional: give the network a specific name

volumes:
  loki-data:
