name: Loki and Grafana CI/CD

# Triggers the workflow on push or pull request events
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


env:
  REGISTRY: ghcr.io

jobs:
  logging:
    runs-on: self-hosted # Use a self-hosted runner
    permissions: # Set permissions for the workflow
      contents: write
    steps:
    - name: Deploy Docker Compose
      run: |
        # Pull the latest images
        docker compose -f logging/logging-docker-compose.yml pull
        # Build and start the containers in detached mode
        docker compose -f logging/logging-docker-compose.yml up -d --remove-orphans --force-recreate
